# Generated by Django 6.0.4 on 2026-04-30 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BANDARA',
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('first_mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PENGGUNA',
            },
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PENYEDIA',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id_tier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('minimal_frekuensi_terbang', models.IntegerField()),
                ('minimal_tier_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'TIER',
            },
        ),
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('kode_maskapai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_maskapai', models.CharField(max_length=100)),
                ('id_penyedia', models.ForeignKey(db_column='id_penyedia', on_delete=django.db.models.deletion.PROTECT, to='green.penyedia')),
            ],
            options={
                'db_table': 'MASKAPAI',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='green.pengguna')),
                ('nomor_member', models.CharField(max_length=20, unique=True)),
                ('tanggal_bergabung', models.DateField()),
                ('award_miles', models.IntegerField(default=0)),
                ('total_miles', models.IntegerField(default=0)),
                ('id_tier', models.ForeignKey(db_column='id_tier', on_delete=django.db.models.deletion.PROTECT, to='green.tier')),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='green.pengguna')),
                ('id_staf', models.CharField(max_length=20, unique=True)),
                ('kode_maskapai', models.ForeignKey(db_column='kode_maskapai', on_delete=django.db.models.deletion.PROTECT, to='green.maskapai')),
            ],
            options={
                'db_table': 'STAF',
            },
        ),
        migrations.CreateModel(
            name='ClaimMissingMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('Premium Economy', 'Premium Economy'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bandara_asal', models.ForeignKey(db_column='bandara_asal', on_delete=django.db.models.deletion.PROTECT, related_name='claims_asal', to='green.bandara')),
                ('bandara_tujuan', models.ForeignKey(db_column='bandara_tujuan', on_delete=django.db.models.deletion.PROTECT, related_name='claims_tujuan', to='green.bandara')),
                ('maskapai', models.ForeignKey(db_column='maskapai', on_delete=django.db.models.deletion.PROTECT, to='green.maskapai')),
                ('email_member', models.ForeignKey(db_column='email_member', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='green.member')),
                ('email_staf', models.ForeignKey(blank=True, db_column='email_staf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_claims', to='green.staf')),
            ],
            options={
                'db_table': 'CLAIM_MISSING_MILES',
                'unique_together': {('email_member', 'flight_number', 'tanggal_penerbangan', 'nomor_tiket')},
            },
        ),
    ]
