# Generated by Django 6.0.4 on 2026-05-15 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMilesPackage',
            fields=[
                ('id_package', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jumlah_miles', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'AWARD_MILES_PACKAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jumlah_miles', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('valid_start', models.DateField()),
                ('program_end', models.DateField()),
            ],
            options={
                'db_table': 'HADIAH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('nomor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_habis', models.DateField()),
                ('tanggal_terbit', models.DateField()),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'IDENTITAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberAwardMilesPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MEMBER_AWARD_MILES_PACKAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
            ],
            options={
                'db_table': 'MITRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hadiah', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Menunggu', max_length=20)),
            ],
            options={
                'db_table': 'REDEEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('email_member_1', models.ForeignKey(db_column='email_member_1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transfers_keluar', serialize=False, to='green.member')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TRANSFER',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bandara',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='claimmissingmiles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='maskapai',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pengguna',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='penyedia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='staf',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tier',
            options={'managed': False},
        ),
    ]
