# Generated by Django 6.0.4 on 2026-05-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitra',
            name='id_penyedia',
        ),
        migrations.DeleteModel(
            name='Hadiah',
        ),
        migrations.DeleteModel(
            name='Mitra',
        ),
    ]
